module Pokedex exposing (..)

import Html exposing (..)
import Html.Attributes exposing (..)


pokedexHtml : Html msg
pokedexHtml =
    div [ id "pokedex" ]
        [ div [ id "left" ]
            [ div [ id "logo" ]
                []
            , div [ id "bg_curve1_left" ]
                []
            , div [ id "bg_curve2_left" ]
                []
            , div [ id "curve1_left" ]
                [ div [ id "buttonGlass" ]
                    [ div [ id "reflect" ]
                        []
                    ]
                , div [ id "miniButtonGlass1" ]
                    []
                , div [ id "miniButtonGlass2" ]
                    []
                , div [ id "miniButtonGlass3" ]
                    []
                ]
            , div [ id "curve2_left" ]
                [ div [ id "junction" ]
                    [ div [ id "junction1" ]
                        []
                    , div [ id "junction2" ]
                        []
                    ]
                ]
            , div [ id "screen" ]
                [ div [ id "topPicture" ]
                    [ div [ id "buttontopPicture1" ]
                        []
                    , div [ id "buttontopPicture2" ]
                        []
                    ]
                , div [ id "picture" ]
                    [ img [ alt "psykokwak", attribute "height" "170", src "https://s3-us-west-2.amazonaws.com/s.cdpn.io/200653/psykokwak.gif" ]
                        []
                    , text "      "
                    ]
                , div [ id "buttonbottomPicture" ]
                    []
                , div [ id "speakers" ]
                    [ div [ class "sp" ]
                        []
                    , div [ class "sp" ]
                        []
                    , div [ class "sp" ]
                        []
                    , div [ class "sp" ]
                        []
                    ]
                ]
            , div [ id "bigbluebutton" ]
                []
            , div [ id "barbutton1" ]
                []
            , div [ id "barbutton2" ]
                []
            , div [ id "cross" ]
                [ div [ id "leftcross" ]
                    [ div [ id "leftT" ]
                        []
                    ]
                , div [ id "topcross" ]
                    [ div [ id "upT" ]
                        []
                    ]
                , div [ id "rightcross" ]
                    [ div [ id "rightT" ]
                        []
                    ]
                , div [ id "midcross" ]
                    [ div [ id "midCircle" ]
                        []
                    ]
                , div [ id "botcross" ]
                    [ div [ id "downT" ]
                        []
                    ]
                ]
            ]
        , div [ id "right" ]
            [ div [ id "stats" ]
                [ strong []
                    [ text "Name :" ]
                , text "Psyduck"
                , br []
                    []
                , strong []
                    [ text "Type :" ]
                , text "Water"
                , br []
                    []
                , strong []
                    [ text "Height :" ]
                , text "2'072''"
                , br []
                    []
                , strong []
                    [ text "Weight :" ]
                , text "43.2 lbs."
                , br []
                    []
                , br []
                    []
                , strong []
                    [ text "The duck Pokemon" ]
                , br []
                    []
                , text "      Uses mysterious powers to perform various attacks.    "
                ]
            , div [ id "miniButtonGlass4" ]
                []
            , div [ id "miniButtonGlass5" ]
                []
            , div [ id "barbutton3" ]
                []
            , div [ id "barbutton4" ]
                []
            , div [ id "yellowBox1" ]
                []
            , div [ id "yellowBox2" ]
                []
            , div [ id "bg_curve1_right" ]
                []
            , div [ id "bg_curve2_right" ]
                []
            , div [ id "curve1_right" ]
                []
            , div [ id "curve2_right" ]
                []
            ]
        ]
